language: node_js
node_js: node
cache:
  npm: false
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  github_token:
    secure: BjIMCmBIEV9EpOl3wAGfIGcq0forakAMC+6WFxB6XZVDhzQkN1V6gLUVLeFEoUbZf6Jg8jdE4MVAJ9wwkzpkb5AemFdYy/6tf0bN7zyaASBSe9whhwK71EJ2dnrcgsvVUPNhLMH3Esufqe1xYwkCgudXhtGDzmRIU3D03BvzyAyRu4GgJzMEZH7ThkPky8XFsWaSAH9PvieHruLy7Ht7cbV2JJSvkZ5qKR2OaKSogCkeJXv2+PLjcgMFRC80CDD0pihZBsO+ES7ofjxwLjTvxdlXuOhwDttrD5WTe9z3GWFBTWIuze43brmHIFnpYOyUHTyeqRsenBlmTmtcIImPJkCKSgusABV5tmopR4okkdN4lNeB0WT9zVcNqiC4D+kBsDdCTWAdm1ik/QZuKNjLc8m5GIUCkDafQ++8SjPbtjuoQL08tJ83Sh0YntdMWbGctwcZj6yYWg8arvNRZTayBFZEIdHM42Ey2zddSNoikeMXzJPQOzPKVPEM2Msh6x/EVxezI9qBoX/B8gA4ZFkcozU3Dj9NDP+h2z4OUZm3JusrQPQCUzukIuDduTdTbrrt4XUNSr8lUGXwyOBYErRVrXJPve9qxV/L+sAe8M3GTcJotAHYpDy0PVIaxIoRMk2c56Up7wTwW3uJfUpQhz8z6/NcUChWMJ+U/h7PlyhSdE4=
