language: node_js
node_js: node
cache:
  npm: false
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  github_token:
    secure: ewWSlQIucDFRwu2Ay5cotU0KDJaIC2FIJEKUuhKg20t9mg5sAQauuHKF6Dmm1iHQgkW/fj6DQ0k/DVH3nIi6sGiwNdm17zGuPg7YaqBck7XgrIIHIdT520O0H3cOyouwBn7P54mh7uJDnBpJd91WwFpG5ZqLM3BfdGjSpC+YWvPaZgCTTmboRBukKhpnsc2Wv64Tv5l/4duclPnL7B+ZoeGHaLrdsX26dCZYsFOBZaConU8aZx3dCH3coOR9KGZqKR4gslEuPJ1k/z6e0924TghziIj/kbg3eQKlzyhjgyCoIgFbMmd4b7ZOn7DU2FZQ94yB/pRxTOfjdjbp0SZEj0aAjC/0WGgI7qipCBXZ7xSGun+KFhYx59lnSItX7ZCacdWfzXHRceTUPzrT08RfYNFXdA3LBdILcTj77qmmt+G4iEEX+/LhlRMbwXiLsbOoVRtkl+3981HIO0wvbRQhUBlR6iUZy+2qv/Fs0d7D+y6srrrWOp3XwaIowdBRFPe/USyWlxcWe1L4DLXWfcs4tdpZWC0SF27HYq/ZewR7mpjG7LRBvRQl9k9g9LBVgWxcFvefhWv3sSMweGSgxDCAPD96gpEbEEvadL2IRxkxbUnGVDP0nzMnsFwmUHJiC1ZHq0Ypcv2m/WrsL8bvNIgfzxdcTDlaLni9I3lmtl8aeBM=
